function setupSkyGameWindow(win) {
  win.classList.add("sky-game-window");
  win.querySelector('[data-action="maximize"]')?.remove();
  const width = Math.min(500, innerWidth - 36), height = Math.min(760, innerHeight - 64);
  win.style.width = `${Math.max(410, width)}px`; win.style.height = `${Math.max(560, height)}px`;
  win.style.left = `${Math.max(6, Math.round((innerWidth - Math.max(410, width)) / 2))}px`; win.style.top = "10px";
  const content = win.querySelector(".window-content");
  content.innerHTML = `<section class="sky-game-shell"><canvas class="sky-game-canvas" width="360" height="600" tabindex="0" aria-label="像素空战游戏画面"></canvas><div class="sky-game-overlay"><h1>PIXEL AIR<small>像素空战</small></h1><p class="sky-game-score"></p><p>W / A / S / D 或方向键移动<br>战机将自动射击</p><button type="button">开始游戏</button></div></section>`;
  const canvas = content.querySelector("canvas"), ctx = canvas.getContext("2d"), overlay = content.querySelector(".sky-game-overlay");
  ctx.imageSmoothingEnabled = false;
  const W=360,H=600, keys=new Set();
  const assetNames={player:"我方飞机.webp",normal:"飞机2.webp",sway:"飞机3.webp",elite:"飞机4.webp",charger:"飞机1.webp",boss:"boss.webp",shot:"弹幕4.webp",enemy1:"弹幕1.webp",enemy2:"弹幕2.webp",enemy3:"弹幕3.webp",enemy5:"弹幕5.webp",boom:"击杀.webp",map1:"第一关地图.webp",map2:"第二关沙漠地图.webp",map3:"第三段雪山地图.webp"};
  const art={}; for(const [key,name] of Object.entries(assetNames)){const img=new Image();img.src=`assets/sky-game/${name}`;art[key]=img;}
  let running=false,last=0,raf=0,score=0,lives=3,stage=1,stageTime=0,spawnClock=0,shotClock=0,scroll=0,invincible=0,banner=0,mapBanner=0,bossSpawned=false,finished=false,mapKey="map1",previousMapKey=null,mapFade=0;
  let player={},bullets=[],enemyBullets=[],enemies=[],explosions=[],stars=[];
  for(let i=0;i<35;i++) stars.push({x:Math.random()*W,y:Math.random()*H,s:1+Math.floor(Math.random()*2)});
  const high=()=>Number(localStorage.getItem("skyStrikerHighScore")||0);
  const setHigh=()=>{if(score>high())localStorage.setItem("skyStrikerHighScore",String(score));};
  let audioCtx=null,masterGain=null,musicTimer=0,musicStep=0;
  function ensureAudio(){if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();masterGain=audioCtx.createGain();masterGain.gain.value=1.75;masterGain.connect(audioCtx.destination);}if(audioCtx.state==="suspended")audioCtx.resume();}
  function tone(freq,duration=.1,type="square",volume=.035,delay=0,endFreq=freq){if(!audioCtx)return;const now=audioCtx.currentTime+delay,osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.setValueAtTime(freq,now);osc.frequency.exponentialRampToValueAtTime(Math.max(30,endFreq),now+duration);gain.gain.setValueAtTime(volume,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain).connect(masterGain);osc.start(now);osc.stop(now+duration+.02);}
  function noise(duration=.12,volume=.04){if(!audioCtx)return;const count=Math.ceil(audioCtx.sampleRate*duration),buffer=audioCtx.createBuffer(1,count,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<count;i++)data[i]=(Math.random()*2-1)*(1-i/count);const src=audioCtx.createBufferSource(),gain=audioCtx.createGain();src.buffer=buffer;gain.gain.value=volume;src.connect(gain).connect(masterGain);src.start();}
  function sound(name){ensureAudio();if(name==="kill"){noise(.14,.022);tone(92,.17,"triangle",.018,0,48);tone(58,.12,"sine",.012,.025,36);}if(name==="hurt"){tone(150,.24,"sawtooth",.055,0,55);noise(.2,.045);}if(name==="win"){[523,659,784,1047].forEach((n,i)=>tone(n,.32,"square",.05,i*.13,n*1.01));}if(name==="fail"){[330,247,196,131].forEach((n,i)=>tone(n,.34,"sawtooth",.04,i*.16,n*.82));}}
  function startMusic(){ensureAudio();clearInterval(musicTimer);musicStep=0;const delay=bossSpawned?142:stage===1?230:185;musicTimer=setInterval(()=>{if(!running||!audioCtx)return;const first=[262,330,392,330,294,349,440,349],second=[294,370,440,587,330,415,494,659],boss=[110,147,165,220,123,165,185,247],notes=bossSpawned?boss:stage===1?first:second,note=notes[musicStep%notes.length];tone(note,bossSpawned?.18:.13,bossSpawned?"sawtooth":"square",bossSpawned?.026:.022);if(musicStep%4===0)tone(note/2,bossSpawned?.38:.28,"triangle",.027);if(bossSpawned&&musicStep%2===1)tone(note*2,.07,"square",.012);musicStep++;},delay);}
  function stopMusic(){clearInterval(musicTimer);musicTimer=0;}
  function start(){ score=0;lives=3;stage=1;stageTime=0;spawnClock=0;shotClock=0;scroll=0;invincible=0;banner=2;mapBanner=0;bossSpawned=false;finished=false;mapKey="map1";previousMapKey=null;mapFade=0; bullets=[];enemyBullets=[];enemies=[];explosions=[];player={x:W/2-32.5,y:H-98,w:65,h:65,speed:220}; overlay.hidden=true;running=true;last=performance.now();canvas.focus();startMusic();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop); }
  function showStart(){overlay.hidden=false;overlay.innerHTML=`<h1>PIXEL AIR<small>像素空战</small></h1><p class="sky-game-score">HIGH SCORE ${String(high()).padStart(6,"0")}</p><p>W / A / S / D 或方向键移动<br>战机将自动射击</p><button type="button">开始游戏</button>`;overlay.querySelector("button").onclick=start;}
  function spawn(type){const info=type==="elite"?{w:86,h:80,hp:7,v:54,points:300}:type==="sway"?{w:88,h:56,hp:2,v:83,points:200}:type==="charger"?{w:76,h:76,hp:3,v:68,points:250}:{w:72,h:80,hp:1,v:74,points:100};let x=null;for(let attempt=0;attempt<14;attempt++){const candidate=12+Math.random()*(W-info.w-24);const crowded=enemies.some(e=>e.type!=="boss"&&e.y<135&&candidate<e.x+e.w+14&&candidate+info.w+14>e.x);if(!crowded){x=candidate;break;}}if(x===null)return;enemies.push({type,x,y:-info.h,...info,t:Math.random()*5,fire:.6+Math.random()*1.5});}
  function spawnBoss(){bossSpawned=true;enemies.push({type:"boss",x:W/2-95,y:-200,w:190,h:182,hp:164,maxHp:164,v:36,points:1000,t:0,fire:.7,pattern:0});banner=2;startMusic();}
  function fireBossVolley(e){const cx=e.x+e.w/2,cy=e.y+e.h-18,pattern=e.pattern++%3;if(pattern===0){[-1,-.5,0,.5,1].forEach(v=>enemyBullets.push({x:cx-9,y:cy,w:18,h:26,vx:v*155,vy:118,art:"enemy1"}));e.fire=1.02;return;}if(pattern===1){const dx=player.x+player.w/2-cx,dy=Math.max(80,player.y-cy),base=Math.atan2(dx,dy);[-.34,0,.34].forEach(a=>enemyBullets.push({x:cx-8,y:cy,w:16,h:23,vx:Math.sin(base+a)*180,vy:Math.cos(base+a)*180,art:"enemy2"}));e.fire=1.14;return;}[-1,-.38,.38,1].forEach((lane,i)=>enemyBullets.push({x:cx+lane*44-8,y:cy+(i%2)*20,w:16,h:22,vx:lane*88,vy:112,art:"enemy3"}));e.fire=.98;}
  function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
  function boom(x,y,big=false){explosions.push({x,y,t:big?.72:.42,big});}
  function damage(){if(invincible>0||!running)return;lives--;invincible=1.5;boom(player.x+10,player.y+14,true);sound("hurt");if(lives<=0)end(false);}
  function end(completed){if(finished)return;finished=true;running=false;stopMusic();sound(completed?"win":"fail");setHigh();const qualify=completed&&score>=5000;if(qualify){let flashes=0;const flash=setInterval(()=>{if(!win.isConnected){clearInterval(flash);return;}canvas.style.filter=flashes%2?"brightness(1)":"brightness(3)";if(++flashes>=8){clearInterval(flash);canvas.style.filter="";overlay.hidden=false;overlay.innerHTML=`<h1 class="access">ACCESS GRANTED</h1><div class="invite">Passcode: FG7A-2001</div><p class="sky-game-score">FINAL SCORE ${String(score).padStart(6,"0")}</p><button type="button">再玩一次</button>`;overlay.querySelector("button").onclick=start;}},140);}else{overlay.hidden=false;overlay.innerHTML=`<h1>${completed?"MISSION COMPLETE":"GAME OVER"}<small>${completed?"SCORE BELOW 5000":"TRY AGAIN"}</small></h1><p class="sky-game-score">SCORE ${String(score).padStart(6,"0")}<br>HIGH SCORE ${String(high()).padStart(6,"0")}</p><button type="button">重新开始</button>`;overlay.querySelector("button").onclick=start;}}
  function update(dt){
    scroll=(scroll+70*dt)%2000;stageTime+=dt;spawnClock-=dt;shotClock-=dt;invincible=Math.max(0,invincible-dt);banner=Math.max(0,banner-dt);mapBanner=Math.max(0,mapBanner-dt);mapFade=Math.max(0,mapFade-dt);
    const dirX=(keys.has("left")?-1:0)+(keys.has("right")?1:0),dirY=(keys.has("up")?-1:0)+(keys.has("down")?1:0);player.x=Math.max(7,Math.min(W-player.w-7,player.x+dirX*player.speed*dt));player.y=Math.max(38,Math.min(H-player.h-8,player.y+dirY*player.speed*dt));
    if(shotClock<=0){shotClock=.135;if(score<4000)bullets.push({x:player.x+27,y:player.y-31,w:18,h:38});else bullets.push({x:player.x+10,y:player.y-28,w:17,h:36},{x:player.x+45,y:player.y-28,w:17,h:36});}
    if(stage===1&&score>=3000){stage=2;stageTime=0;spawnClock=.8;enemies=[];enemyBullets=[];bossSpawned=false;banner=2.5;startMusic();}
    if(stage===2&&stageTime>=41&&!bossSpawned)spawnBoss();
    if(spawnClock<=0 && !(stage===2&&stageTime>43)){const r=Math.random();spawn(stage===1?(r<.56?"normal":r<.78?"sway":r<.93?"charger":"elite"):(r<.34?"normal":r<.61?"sway":r<.82?"charger":"elite"));spawnClock=(stage===1?.62:.43)+Math.random()*.25;}
    bullets.forEach(b=>b.y-=330*dt);enemyBullets.forEach(b=>{b.x+=(b.vx||0)*dt;b.y+=(b.vy||145)*dt;});
    enemies.forEach(e=>{e.t+=dt;if(e.type==="boss"){if(e.y<42)e.y+=e.v*dt;else e.x=W/2-e.w/2+Math.sin(e.t*.82)*76;e.fire-=dt;if(e.fire<=0)fireBossVolley(e);}else{e.y+=e.v*dt;if(e.type==="sway")e.x+=Math.sin(e.t*4)*62*dt;if(e.type==="charger")e.x+=Math.sin(e.t*2.3)*34*dt;e.fire-=dt;if(e.fire<=0){const baseFire=e.type==="elite"?1.05:e.type==="sway"?1.55:e.type==="charger"?1.3:1.85;e.fire=stage===2?baseFire*.68:baseFire;const isCharger=e.type==="charger",baseSpeed=(isCharger?240:150)*(stage===2?1.28:1),cx=e.x+e.w/2,cy=e.y+e.h-4;const angled=stage===2&&(e.type==="sway"||e.type==="elite")&&Math.random()<.6;const dx=player.x+player.w/2-cx,dy=Math.max(90,player.y-cy),angle=angled?Math.max(-.42,Math.min(.42,Math.atan2(dx,dy))):0;enemyBullets.push({x:cx-(isCharger?5.5:9),y:cy,w:isCharger?11:18,h:isCharger?60:26,vx:Math.sin(angle)*baseSpeed,vy:Math.cos(angle)*baseSpeed,art:e.type==="elite"?"enemy3":e.type==="sway"?"enemy2":isCharger?"enemy5":"enemy1"});}}});
    for(const b of bullets)for(const e of enemies){if(!b.dead&&!e.dead&&hit(b,e)){b.dead=true;e.hp--;if(e.hp<=0){e.dead=true;score+=e.points;boom(e.x+e.w/2,e.y+e.h/2,e.type==="boss");sound("kill");if(e.type==="boss")setTimeout(()=>{if(win.isConnected)end(true)},550);}}}
    for(const e of enemies){if(!e.dead&&hit(player,e)){e.dead=true;boom(e.x+e.w/2,e.y+e.h/2,e.type==="boss");damage();}}
    for(const b of enemyBullets)if(!b.dead&&hit(player,b)){b.dead=true;damage();}
    explosions.forEach(e=>e.t-=dt);bullets=bullets.filter(b=>!b.dead&&b.y>-15);enemyBullets=enemyBullets.filter(b=>!b.dead&&b.y<H+15&&b.x>-20&&b.x<W+20);enemies=enemies.filter(e=>!e.dead&&e.y<H+70);explosions=explosions.filter(e=>e.t>0);
  }
  function pixelText(text,x,y,size=13,align="left",color="#fff"){ctx.font=`bold ${size}px Courier New`;ctx.textAlign=align;ctx.fillStyle="#102256";ctx.fillText(text,x+2,y+2);ctx.fillStyle=color;ctx.fillText(text,x,y);}
  function drawMap(img,alpha=1){if(!img?.complete||!img.naturalWidth)return;const scaledH=H*img.naturalHeight/img.naturalWidth,offset=scroll%scaledH;ctx.globalAlpha=alpha;ctx.drawImage(img,0,offset-scaledH,W,scaledH);ctx.drawImage(img,0,offset,W,scaledH);if(offset+scaledH<H)ctx.drawImage(img,0,offset+scaledH,W,scaledH);ctx.globalAlpha=1;}
  function background(){const desired=score>=12000?"map3":stage===1?"map1":"map2";if(desired!==mapKey){if(mapKey==="map2"&&desired==="map3")mapBanner=2.7;previousMapKey=mapKey;mapKey=desired;mapFade=1.25;}ctx.fillStyle="#58aee6";ctx.fillRect(0,0,W,H);drawMap(art[mapKey]);if(previousMapKey&&mapFade>0)drawMap(art[previousMapKey],mapFade/1.25);if(mapFade<=0)previousMapKey=null;}
  function drawPlayer(){if(invincible>0&&Math.floor(invincible*12)%2===0)return;if(art.player.complete)ctx.drawImage(art.player,Math.round(player.x),Math.round(player.y),player.w,player.h);}
  function drawEnemy(e){const sprite=art[e.type];if(sprite?.complete)ctx.drawImage(sprite,Math.round(e.x),Math.round(e.y),e.w,e.h);}
  function draw(){background();for(const b of bullets){if(art.shot.complete)ctx.drawImage(art.shot,Math.round(b.x),Math.round(b.y),b.w,b.h);}for(const b of enemyBullets){const sprite=art[b.art||"enemy1"];if(sprite?.complete){ctx.save();ctx.translate(Math.round(b.x+b.w/2),Math.round(b.y+b.h/2));ctx.rotate(-Math.atan2(b.vx||0,b.vy||145));ctx.drawImage(sprite,-b.w/2,-b.h/2,b.w,b.h);ctx.restore();}}enemies.forEach(drawEnemy);drawPlayer();for(const e of explosions){const life=e.big?.72:.42,p=1-e.t/life,size=(e.big?92:58)*(1+Math.min(1,p)*.18);ctx.globalAlpha=Math.min(1,e.t/.16);if(art.boom.complete)ctx.drawImage(art.boom,e.x-size/2,e.y-size/2,size,size);ctx.globalAlpha=1;}ctx.fillStyle="rgba(5,17,54,.82)";ctx.fillRect(0,0,W,30);pixelText(`SCORE ${String(score).padStart(6,"0")}`,8,20,13);pixelText(`LIFE ${"▲".repeat(Math.max(0,lives))}`,178,20,13,"center","#fff36a");pixelText(`STAGE ${stage}`,351,20,13,"right");const boss=enemies.find(e=>e.type==="boss");if(boss){ctx.fillStyle="#172451";ctx.fillRect(69,38,222,13);ctx.fillStyle="#e84552";ctx.fillRect(72,41,216*Math.max(0,boss.hp/boss.maxHp),7);pixelText("BOSS",W/2,65,11,"center","#fff36a");}if(banner>0||mapBanner>0){ctx.fillStyle="rgba(5,12,40,.58)";ctx.fillRect(0,H/2-34,W,68);pixelText(banner>0?(stage===2&&bossSpawned?"WARNING! BOSS":"STAGE "+stage):"FINAL AREA",W/2,H/2+8,25,"center","#fff36a");}}
  function loop(now){if(!win.isConnected)return;const dt=Math.min(.033,(now-last)/1000||0);last=now;if(running)update(dt);draw();if(running)raf=requestAnimationFrame(loop);}
  const normalizeKey=e=>e.key==="ArrowLeft"||e.key.toLowerCase()==="a"?"left":e.key==="ArrowRight"||e.key.toLowerCase()==="d"?"right":e.key==="ArrowUp"||e.key.toLowerCase()==="w"?"up":e.key==="ArrowDown"||e.key.toLowerCase()==="s"?"down":"";
  const keydown=e=>{const key=normalizeKey(e);if(key){e.preventDefault();e.stopPropagation();keys.add(key);canvas.focus();}};
  const keyup=e=>{const key=normalizeKey(e);if(key){e.preventDefault();keys.delete(key);}};
  window.addEventListener("keydown",keydown,true);window.addEventListener("keyup",keyup,true);canvas.addEventListener("pointerdown",()=>canvas.focus());
  const observer=new MutationObserver(()=>{if(win.isConnected)return;cancelAnimationFrame(raf);stopMusic();if(audioCtx&&audioCtx.state!=="closed")audioCtx.close();window.removeEventListener("keydown",keydown,true);window.removeEventListener("keyup",keyup,true);observer.disconnect();});observer.observe(document.body,{childList:true,subtree:true});
  showStart();draw();
}
